# Use a stable base image
FROM alpine:3.19

# Install the main lighttpd package
RUN apk update && apk add lighttpd

# Create the directory for your CGI binaries and symlinks
WORKDIR /app/
RUN mkdir cgi-bin

# Copy your binaries and the symlinks into the container
COPY cgi-bin/ /app/cgi-bin/

# Change the ownership of the files to the lighttpd user and group
# This is the correct way to fix the permission denied error
RUN chown -R lighttpd:lighttpd /app/cgi-bin

# Copy your custom lighttpd configuration file
COPY lighttpd.conf /etc/lighttpd/lighttpd.conf

# Grant execute permissions to your C apps
RUN chmod +x \
    /app/cgi-bin/onvif_simple_server \
    /app/cgi-bin/onvif_notify_server \
    /app/cgi-bin/wsd_simple_server

RUN ln -s /app/cgi-bin/onvif_simple_server /app/cgi-bin/device_service.cgi; \
    ln -s /app/cgi-bin/onvif_simple_server /app/cgi-bin/media_service.cgi; \
    ln -s /app/cgi-bin/onvif_simple_server /app/cgi-bin/media2_service.cgi; \
    ln -s /app/cgi-bin/onvif_simple_server /app/cgi-bin/ptz_service.cgi; \
    ln -s /app/cgi-bin/onvif_simple_server /app/cgi-bin/deviceio_service.cgi; \
    ln -s /app/cgi-bin/onvif_simple_server /app/cgi-bin/events_service.cgi

# Expose the port for the web server
EXPOSE 8000

# Command to run the Lighttpd server when the container starts
CMD ["lighttpd", "-D", "-f", "/etc/lighttpd/lighttpd.conf"]
